### ISSUE TITLE
Recommendations for maintaining external databases?

### ISSUE THREAD

**Issue by jaimeebeckett** [WGLab/phenolyzer#16]
Hello, 

I would like to use this tool but noticed the external databases have not been updated in a while. Are there any recommendations for maintaining these?

**Comment by kaichop** [comment]
We will try to update the external databases and build a new prediction
model. It is not straightforward for users to build updated database
yourself since there are many formatting changes of the various external
datasets.

**Comment by moe1619** [comment]
If we would like to use this tool but would like to use it with regularly updated databases, what would you recommend? Should we figure out how to do the updates ourselves (hopefully with your help)? or is it possible for your team to update regularly? Thank you so much for making this fantastic tool available.

**Comment by moe1619** [comment]
Hello, just checking in on this. Thanks.

**Comment by moe1619** [comment]
I started a related issue in EHR-phenolyzer
https://github.com/WGLab/EHR-Phenolyzer/issues/14

Thanks!

**Comment by kaichop** [comment]
I have tentatively pushed a `updatedb_20230107` branch with some testing. The number of records in the old version and new version is given below. Additionally, the hpo.obo and doid.obo files are updated to 2023 version. The formats and certain keywords for some of the original databases have been changed; to be backwards compatible with old versions of Phenolyzer, appropriate care has been taken to modify some of the DB files below.

```
61370 207792 DB_HUMAN_GENE_ID
36558 75784 DB_GWAS_GENE_DISEASE
6179 7135 DB_CLINVAR_GENE_DISEASE
7273 8059 DB_OMIM_GENE_DISEASE
5714 8248 DB_ORPHANET_GENE_DISEASE
55219 92845 DB_COMPILED_GENE_DISEASE_SCORE
113724 252457 DB_HPO_ANNOTATION
```

Down the road, I will try to clean up the file preparation scripts so that users can use them to update databases, as it currently involves a lot of manual steps. Additionally, some of the databases probably should be switched to other choices, for example, biosystems pathway database has not been changed since 2017 in NIH website. 

Please test the new version and see if there is any issues. Thank you very much for your interests in the tool. If there is no major issues, I will merge this into master branch soon, and then update Phen2Gene as well.

**Comment by moe1619** [comment]
Thanks so much. We'll take a look.

**Comment by nickzren** [comment]
Very helpful, we will test it and let you know.

**Comment by jaimeebeckett** [comment]
Thank you! We tested the new version and do not see any issues.

**Comment by kaichop** [comment]
Thank you! This is greatly appreciated.
